### PR TITLE
tdlib 1.8.12 #348

### PR DESCRIPTION
**Pull request by JleMyP**
Hi! I updated tdlib authorization flow to 1.8.12 https://github.com/tdlib/td/commit/0c09070ce5d36bcccc5533c89dea45909483f45a and added binaries for linux, but i have no way to build binaries for macos

### CODE REVIEW

**Comment by alexander-akhmetov** [comment]
Hi! Thanks a lot for the pull request! I was wondering if it's possible to support both the old and new ways at the same time, in case some users prefer to use their own version of `tdlib` instead of the embedded binaries. There is a `getVersion` method, but it seems to require authorization first.

Could you please keep both the `parameters` key and the new keys at the same time in the `data` dictionary for compatibility between both tdlib versions? Something like this should work I believe:

```python
  def __init__(...)
      ....
      self._database_encryption_key = database_encryption_key

      if isinstance(self._database_encryption_key, str):
          self._database_encryption_key = self._database_encryption_key.encode()

      self._database_encryption_key = base64.b64encode(self._database_encryption_key).decode()
      ...

  def _set_initial_params(self) -> AsyncResult:
      ...
      parameters = {
          'use_test_dc': self.use_test_dc,
          'api_id': self.api_id,
          'api_hash': self.api_hash,
          'device_model': self.device_model,
          'system_version': self.system_version,
          'application_version': self.application_version,
          'system_language_code': self.system_language_code,
          'database_directory': os.path.join(self.files_directory, 'database'),
          'use_message_database': self.use_message_database,
          'files_directory': os.path.join(self.files_directory, 'files'),
          'use_secret_chats': self.use_secret_chats,
          'database_encryption_key': self._database_encryption_key,
      }

      data = {
          '@type': 'setTdlibParameters',
          'parameters': parameters,
      }
      # for backward compatibility with tdlib < 1.8.6
      data.update(parameters)

      return self._send_data(data, result_id='updateAuthorizationState')

  def _send_encryption_key(self) -> AsyncResult:
      logger.info('Sending encryption key')

      data = {
          '@type': 'checkDatabaseEncryptionKey',
          'encryption_key': self._database_encryption_key,
      }

      return self._send_data(data, result_id='updateAuthorizationState')
```

Otherwise I'd have to bump the major version because the library wouldn't work with both versions.

Also, don't worry about the binaries, you don't need to include them in the PR, I'll build them.

**Comment by alexander-akhmetov** [comment]
Thank you, it looks great! Could you remove the binaries before we merge it please?

**Comment by JleMyP** [comment]
aarch64 remove too? it is useful for android and SBC computers like raspberry pi

**Comment by alexander-akhmetov** [comment]
Yes, please. I would like to avoid merging binaries. `aarch64` is indeed useful. I am working on a pipeline that will build binaries using GitHub Actions, and I will add it there.

**Comment by alexander-akhmetov** [comment]
Thanks!

**Review by alexander-akhmetov — APPROVED** [review]

**Pull request merged**
